name: PR Python (uv)
on:
  pull_request:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Set up uv
        uses: astral-sh/setup-uv@v4

      - name: Sync dependencies (frozen)
        run: uv sync --frozen

      - name: Smoke check
        env:
          PYTHONPATH: src
        run: |
          uv run python --version
          uv run python -m load_everything -h
